### ISSUE TITLE
Simple idea for a first iteration of an LFE stdlb

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#108]
For context, see parent task, #107.

In LFE:
- [x] Create a `lib` or `stdlib` directory in the LFE code base
- [x] Add a `README` to explain what it does
- [x] Add a `Makefile` so that the appropriate top-level LFE `make` targets can `cd` and compile the libraries
- [x] In the stdlib `Makefile`, add a variable that will hold a list of the set of libraries that will comprise the stdlib
- [x] In the stdlib `Makefile`, add a target for downloading LFE libraries for the stdlib
- [x] In the stdlib `Makefile`, add a target for compiling LFE libraries for the stdlib
- [x] Compile all libs to the LFE `ebin` dir
- [x] Copy the libs' `include` files to LFE `include` dir
- [x] Add a new top-level `make` target for LFE (e.g., `make stdlib`) that will build the defined libraries

In the "lfe" Github org:
- [ ] Copy some libraries (wholesale or in part) to the "lfe" org on github
- [ ] Prefix these repo names with "stdlib-" (self-documenting, for purposes of clarity)
- [ ] Pare down these repos so simply include (1) a `README` (which will eventually contain or link to complete documentation for the library), (2) a `src` dir containing LFE modues, and (3) an optional `include` dir containing macros, functions, records, etc.

For both:
- [x] Step through a standard LFE build, and make sure everything works
- [ ] Iron out bugs or issues with the `make stdlib` target
- [ ] Ensure that the standard LFE build still works
- [ ] Ask @rvirding to give it a whirl :-)

**Comment by oubiwann** [comment]
Work is being done in this branch:
- https://github.com/lfe/lfe/tree/stdlib-experiment

**Comment by oubiwann** [comment]
I've got this running against "lfex" github org libraries. If this is something we want to continue looking at, I'll need to copy those repos into the "lfe" github org, and update their include-lib paths (since those are breaking right now ... since they are part of the LFE paths in this setup, the include paths need to be changed to reflect this).

Also, a rename of modules, etc., would be necessary so they didn't clash with the modules in the "lfex" org. This would be just as simple as dropping the initial "l" from the module names.

**Comment by oubiwann** [comment]
This ended up being done for `cl.lfe` and `clj.lfe`.

Closing ...
