### ISSUE TITLE
Update docs for 2.x

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#432]
Tasks:

* [x] Update all docs / books with 2.0 version numbers, book covers, and new blue stylings (with the PDP-11!)
   * [x] Create new theme with own repo - https://github.com/cnbbooks/lfe-book-theme
   * [x] Follow the instructions for updating, here: https://github.com/cnbbooks/lfe-book-theme/issues/2
   * [x] Update https://github.com/cnbbooks/lfe-casting-spels/issues/34
   * [ ] Update https://github.com/cnbbooks/lfe-tutorial/issues/17
   * [x] Update https://github.com/cnbbooks/lfe-rebar3-command-reference/issues/9
   * [x] Update https://github.com/cnbbooks/lfe-style-guide/issues/8
   * [x] Update https://github.com/cnbbooks/lfe-sicp/issues/25
   * [x] Update https://github.com/cnbbooks/lfe-rebar3-quick-start/issues/16
   * [ ] Update https://github.com/cnbbooks/lfe-manual/issues/26
* [ ] Update latest commit ids for books https://github.com/lfe/books/issues/2
* [x] Update latest commit ids for references https://github.com/lfe/reference/issues/2
* [x] Update the book cover images in the "Books" section on lfe.io

**Comment by oubiwann** [comment]
Calling it.
